In [9]:

# 1)	Define the following metrics and perform the following operations
 i)	Write a Python program using Python Lists
 ii)	Write a Python program and NumPy

 Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
 [1.1234  2.8934,  5.9087]].

 Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

 Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
 [1.1254  2.8956,  5.9187]].



import cProfile
import pstats

# Define matrices A, B, and C using Python lists
A = [
    [3.7827, 3.3454, 3.2341],
    [2.2122, 3.5678, 3.9087],
    [1.1234, 2.8934, 5.9087]
]

B = [
    [3.1234, 3.0987, 3.1234],
    [2.1111, 3.2222, 3.3333],
    [1.0987, 1.3456, 5.1234]
]

C = [
    [3.1243, 3.0989, 3.1256],
    [2.6721, 3.6785, 3.9017],
    [1.1254, 2.8956, 5.9187]
]

# Function to add two matrices element-wise
def elementwise_operation(matrix1, matrix2, operation):
    result_matrix = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            if operation == "add":
                row.append(matrix1[i][j] + matrix2[i][j])
            elif operation == "subtract":
                row.append(matrix1[i][j] - matrix2[i][j])
            elif operation == "multiply":
                row.append(matrix1[i][j] * matrix2[i][j])
        result_matrix.append(row)
    return result_matrix

def perform_operations():
    # Perform matrix operations
    sum_AB = elementwise_operation(A, B, "add")
    diff_AB = elementwise_operation(A, B, "subtract")
    prod_AB = elementwise_operation(A, B, "multiply")

    # Print results
    print("Matrix Addition A + B:", sum_AB)
    print("Matrix Subtraction A - B:", diff_AB)
    print("Matrix Element-wise Multiplication A * B:", prod_AB)

# Profile the perform_operations function
cProfile.run('perform_operations()', 'profile_list_stats')

# Print the profiling results
p = pstats.Stats('profile_list_stats')
p.strip_dirs().sort_stats('cumulative').print_stats(10)


Matrix Addition A + B: [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]
Matrix Subtraction A - B: [[0.6593, 0.24670000000000014, 0.11070000000000002], [0.10110000000000019, 0.34560000000000013, 0.5754000000000001], [0.024699999999999944, 1.5478000000000003, 0.7852999999999994]]
Matrix Element-wise Multiplication A * B: [[11.814885180000001, 10.36639098, 10.10138794], [4.6701754200000005, 11.49616516, 13.02886971], [1.23427958, 3.89335904, 30.27263358]]
Wed Sep  4 09:55:19 2024    profile_list_stats

         335 function calls (332 primitive calls) in 0.004 seconds

   Ordered by: cumulative time
   List reduced from 85 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.004    0.004 {method '__exit__' of 'sqlite3.Connection' objects}
      2/1    0.002    0.001    0.002    0.002 {built-in method builtins.exec}
        1    0.000    0.000    0.002    0.002 <string>:

In [ ]:
#ii) 	Write a Python program and NumPy

In [11]:
import numpy as np
import cProfile
import pstats

# Define matrices A, B, and C using NumPy arrays
A_np = np.array([
    [3.7827, 3.3454, 3.2341],
    [2.2122, 3.5678, 3.9087],
    [1.1234, 2.8934, 5.9087]
])

B_np = np.array([
    [3.1234, 3.0987, 3.1234],
    [2.1111, 3.2222, 3.3333],
    [1.0987, 1.3456, 5.1234]
])

C_np = np.array([
    [3.1243, 3.0989, 3.1256],
    [2.6721, 3.6785, 3.9017],
    [1.1254, 2.8956, 5.9187]
])

# Function to perform matrix operations using NumPy and operation type
def numpy_operation(matrix1, matrix2, operation):
    if operation == "add":
        return np.add(matrix1, matrix2)
    elif operation == "subtract":
        return np.subtract(matrix1, matrix2)
    elif operation == "multiply":
        return np.multiply(matrix1, matrix2)  # Element-wise multiplication

def perform_numpy_operations():
    # Perform matrix operations
    sum_AB_np = numpy_operation(A_np, B_np, "add")
    diff_AB_np = numpy_operation(A_np, B_np, "subtract")
    prod_AB_np = numpy_operation(A_np, B_np, "multiply")

    # Print results
    print("\nMatrix Addition A + B (NumPy):\n", sum_AB_np)
    print("\nMatrix Subtraction A - B (NumPy):\n", diff_AB_np)
    print("\nMatrix Element-wise Multiplication A * B (NumPy):\n", prod_AB_np)

# Profile the perform_numpy_operations function
cProfile.run('perform_numpy_operations()', 'profile_numpy_stats')

# Print the profiling results
p = pstats.Stats('profile_numpy_stats')
p.strip_dirs().sort_stats('cumulative').print_stats(10)



Matrix Addition A + B (NumPy):
 [[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]

Matrix Subtraction A - B (NumPy):
 [[0.6593 0.2467 0.1107]
 [0.1011 0.3456 0.5754]
 [0.0247 1.5478 0.7853]]

Matrix Element-wise Multiplication A * B (NumPy):
 [[11.81488518 10.36639098 10.10138794]
 [ 4.67017542 11.49616516 13.02886971]
 [ 1.23427958  3.89335904 30.27263358]]
Wed Sep  4 09:56:02 2024    profile_numpy_stats

         1333 function calls (1291 primitive calls) in 0.022 seconds

   Ordered by: cumulative time
   List reduced from 161 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.001    0.000    0.036    0.012 {built-in method builtins.print}
        3    0.001    0.000    0.033    0.011 arrayprint.py:1666(_array_str_implementation)
        1    0.000    0.000    0.021    0.021 <string>:1(<module>)
        1    0.000    0.000    0.021    0.021 2836620677.py:33(perform_numpy_operations)
 

In [ ]:
# 2)	Write a Python Program and perform the following operations ?
I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}
II.	Iterate using a for loop
III.	Iterate using for loop and range
IV.	List Comprehension
V.	Enumerate
VI.	Iter function and next function
VII.	Map function
VIII.	Using zip
IX.	Using NumPy Module


In [27]:
#normal 
import numpy as np
import cProfile
import pstats
from io import StringIO

# I. Create a List
swetha_list = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# Function to iterate using a for loop
def iterate_for_loop():
    print("Iterating using a for loop:")
    for number in swetha_list:
        print(number)

# Function to iterate using a for loop and range
def iterate_for_loop_range():
    print("\nIterating using a for loop and range:")
    for i in range(len(swetha_list)):
        print(swetha_list[i])

# Function to perform list comprehension
def list_comprehension():
    print("\nList comprehension result (squares of the numbers):")
    squares = [x**2 for x in swetha_list]
    print(squares)

# Function to use enumerate
def use_enumerate():
    print("\nUsing enumerate:")
    for index, value in enumerate(swetha_list):
        print(f"Index {index}: Value {value}")

# Function to use iter() and next()
def use_iter_next():
    print("\nUsing iter() and next():")
    swetha_iter = iter(swetha_list)
    for _ in range(len(swetha_list)):
        print(next(swetha_iter))

# Function to use map()
def use_map():
    print("\nUsing map() function (multiply each element by 2):")
    doubled = list(map(lambda x: x * 2, swetha_list))
    print(doubled)

# Function to use zip
def use_zip():
    print("\nUsing zip (pairing each element with its index):")
    zipped = list(zip(range(len(swetha_list)), swetha_list))
    print(zipped)

# Function to use NumPy
def use_numpy():
    print("\nUsing NumPy Module (convert list to NumPy array and perform operations):")
    swetha_array = np.array(swetha_list)
    print("Original NumPy array:", swetha_array)
    print("Array + 10:", swetha_array + 10)
    print("Array squared:", swetha_array ** 2)

# Profiling the functions
def profile_code():
    # Profile the iterate_for_loop function
    print("Profile results for iterate_for_loop:")
    pr = cProfile.Profile()
    pr.enable()
    iterate_for_loop()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the iterate_for_loop_range function
    print("Profile results for iterate_for_loop_range:")
    pr = cProfile.Profile()
    pr.enable()
    iterate_for_loop_range()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the list_comprehension function
    print("Profile results for list_comprehension:")
    pr = cProfile.Profile()
    pr.enable()
    list_comprehension()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the use_enumerate function
    print("Profile results for use_enumerate:")
    pr = cProfile.Profile()
    pr.enable()
    use_enumerate()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the use_iter_next function
    print("Profile results for use_iter_next:")
    pr = cProfile.Profile()
    pr.enable()
    use_iter_next()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the use_map function
    print("Profile results for use_map:")
    pr = cProfile.Profile()
    pr.enable()
    use_map()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the use_zip function
    print("Profile results for use_zip:")
    pr = cProfile.Profile()
    pr.enable()
    use_zip()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the use_numpy function
    print("Profile results for use_numpy:")
    pr = cProfile.Profile()
    pr.enable()
    use_numpy()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

# Run the profiling
profile_code()



Profile results for iterate_for_loop:
Iterating using a for loop:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456
         255 function calls in 0.001 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       22    0.000    0.000    0.000    0.000 C:\Users\Kavitha\AppData\Roaming\Python\Python312\site-packages\ipykernel\iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
       22    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
       11    0.000    0.000    0.001    0.000 {built-in method builtins.print}
       22    0.000    0.000    0.000    0.000 C:\Users\Kavitha\AppData\Roaming\Python\Python312\site-packages\ipykernel\iostream.py:505(parent_header)
       22    0.000    0.000    0.000    0.000 C:\Users\Kavitha\AppData\Roaming\Python\Python312\site-packages\ipykernel\iostream.py:550(_is_master_process)
       22    0.000    0.000  

In [ ]:
# 3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [23]:
import itertools
import cProfile

# Lists A, B, C, D, E
list_Alpha = 'A'
list_Beta = 'B'
list_Charlie = 'C'
list_Delta = 'D'
list_Echo = 'E'

# Combine all the lists (actually, the list names) into one list
combined_list = [list_Alpha, list_Beta, list_Charlie, list_Delta, list_Echo]

# Function to compute all combinations
def compute_combinations():
    print("\nAll combinations:")
    for combo_size in range(1, len(combined_list) + 1):
        combinations = list(itertools.combinations(combined_list, combo_size))
        print(f"Combinations of {combo_size} elements: {combinations}")

# Function to compute all permutations
def compute_permutations():
    print("\nAll permutations:")
    for perm_size in range(1, len(combined_list) + 1):
        permutations = list(itertools.permutations(combined_list, perm_size))
        print(f"Permutations of {perm_size} elements: {permutations}")

# Profiling the functions
print("Profile results for compute_combinations:")
cProfile.run('compute_combinations()')

print("\nProfile results for compute_permutations:")
cProfile.run('compute_permutations()')


Profile results for compute_combinations:

All combinations:
Combinations of 1 elements: [('A',), ('B',), ('C',), ('D',), ('E',)]
Combinations of 2 elements: [('A', 'B'), ('A', 'C'), ('A', 'D'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'D'), ('C', 'E'), ('D', 'E')]
Combinations of 3 elements: [('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'B', 'E'), ('A', 'C', 'D'), ('A', 'C', 'E'), ('A', 'D', 'E'), ('B', 'C', 'D'), ('B', 'C', 'E'), ('B', 'D', 'E'), ('C', 'D', 'E')]
Combinations of 4 elements: [('A', 'B', 'C', 'D'), ('A', 'B', 'C', 'E'), ('A', 'B', 'D', 'E'), ('A', 'C', 'D', 'E'), ('B', 'C', 'D', 'E')]
Combinations of 5 elements: [('A', 'B', 'C', 'D', 'E')]
         143 function calls in 0.001 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 1569603692.py:15(compute_combinations)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
       12    0.000    0.000

In [ ]:
#4) 	Using the same list use itertools compute permutations and combinations 

In [25]:
import itertools
import cProfile
import pstats
from io import StringIO

# List names
list_Alpha = 'A'
list_Beta = 'B'
list_Charlie = 'C'
list_Delta = 'D'
list_Echo = 'E'

# Combine all the lists (actually, the list names) into one list
combined_list = [list_Alpha, list_Beta, list_Charlie, list_Delta, list_Echo]

# Function to compute all combinations
def compute_combinations():
    print("\nAll combinations:")
    for combo_size in range(1, len(combined_list) + 1):
        combinations = list(itertools.combinations(combined_list, combo_size))
        print(f"Combinations of {combo_size} elements: {combinations}")

# Function to compute all permutations
def compute_permutations():
    print("\nAll permutations:")
    for perm_size in range(1, len(combined_list) + 1):
        permutations = list(itertools.permutations(combined_list, perm_size))
        print(f"Permutations of {perm_size} elements: {permutations}")

# Profiling the functions
def profile_code():
    # Profile the combination function
    print("Profile results for compute_combinations:")
    pr = cProfile.Profile()
    pr.enable()
    compute_combinations()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

    # Profile the permutation function
    print("Profile results for compute_permutations:")
    pr = cProfile.Profile()
    pr.enable()
    compute_permutations()
    pr.disable()
    s = StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.TIME)
    ps.print_stats()
    print(s.getvalue())

# Run the profiling
profile_code()


Profile results for compute_combinations:

All combinations:
Combinations of 1 elements: [('A',), ('B',), ('C',), ('D',), ('E',)]
Combinations of 2 elements: [('A', 'B'), ('A', 'C'), ('A', 'D'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'D'), ('C', 'E'), ('D', 'E')]
Combinations of 3 elements: [('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'B', 'E'), ('A', 'C', 'D'), ('A', 'C', 'E'), ('A', 'D', 'E'), ('B', 'C', 'D'), ('B', 'C', 'E'), ('B', 'D', 'E'), ('C', 'D', 'E')]
Combinations of 4 elements: [('A', 'B', 'C', 'D'), ('A', 'B', 'C', 'E'), ('A', 'B', 'D', 'E'), ('A', 'C', 'D', 'E'), ('B', 'C', 'D', 'E')]
Combinations of 5 elements: [('A', 'B', 'C', 'D', 'E')]
         141 function calls in 0.000 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       12    0.000    0.000    0.000    0.000 C:\Users\Kavitha\AppData\Roaming\Python\Python312\site-packages\ipykernel\iostream.py:655(write)
        1    0.000    0.000    0.000